extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_f3dlite_material_lights;
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_1_vtx_0[201];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
